<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-12-06T12:40:19 IST" name="SmokeTest" finished-at="2024-12-06T12:40:36 IST" duration-ms="16834">
    <groups>
    </groups>
    <test started-at="2024-12-06T12:40:19 IST" name="Logintest" finished-at="2024-12-06T12:40:36 IST" duration-ms="16834">
      <class name="com.OrangeHRM.testcases.CartTest">
        <test-method is-config="true" signature="launchapp()[pri:0, instance:com.OrangeHRM.testcases.CartTest@6c37bd27]" started-at="2024-12-06T12:40:19 IST" name="launchapp" finished-at="2024-12-06T12:40:22 IST" duration-ms="2951" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchapp -->
        <test-method signature="validatecart(java.lang.Object)[pri:0, instance:com.OrangeHRM.testcases.CartTest@6c37bd27]" started-at="2024-12-06T12:40:22 IST" name="validatecart" data-provider="logindata" finished-at="2024-12-06T12:40:32 IST" duration-ms="10182" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Email=vprsaran@gmail.com, Tabtitle=Automation Exercise - Checkout, Tabnames=Cart, Password=Testing@123}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.OrangeHRM.Utilities.ActionEngine.assertEqualsString_custom(ActionEngine.java:196)
at com.OrangeHRM.testcases.CartTest.validatecart(CartTest.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validatecart -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.OrangeHRM.testcases.CartTest@6c37bd27]" started-at="2024-12-06T12:40:35 IST" name="teardown" finished-at="2024-12-06T12:40:36 IST" duration-ms="546" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.OrangeHRM.testcases.CartTest -->
    </test> <!-- Logintest -->
  </suite> <!-- SmokeTest -->
</testng-results>
